### ISSUE TITLE
apidocs redirecting to dedupe docs

### ISSUE THREAD

**Issue by derekeder** [dedupeio/dedupeio-web-api-docs#9]
Right now, when you go to https://apidocs.dedupe.io, it redirects you to https://docs.dedupe.io.

Both documentation sites are hosted on 52.0.77.67. Perhaps this is a server configuration issue?

**Comment by jeancochrane** [comment]
Alright, I think I got this figured out. In the Nginx configuration for the RTD upstream proxy, we were assigning the wrong project slug:

```diff
<         proxy_set_header X-RTD-SLUG dedupe;  # Substitute your project's slug here
>         proxy_set_header X-RTD-SLUG dedupe-web-api;  # Substitute your project's slug here
```

This was causing RTD to treat https://docs.dedupe.io/ as the upstream proxy for https://apidocs.dedupe.io.

As far as I can tell these configuration files aren't under version control anywhere, so I just edited them on the server. If you visit https://apidocs.dedupe.io/en/latest and give it a hard refresh you should be able to see the correct docs load.

**Comment by derekeder** [comment]
This seems to have resolved the issue.

My question is - is this new or was it always in place? If it was already there, I wonder why I ever saw the web api docs at that URL

**Comment by jeancochrane** [comment]
Yeah, I'm not sure why this configuration ever would have worked.
